### ISSUE TITLE
 ExpectedExceptionExtension should match subtypes as well

### ISSUE THREAD

**Issue by sbrannen** [glytching/junit-extensions#5]
## Expected Behavior

As with a `try-catch` clause in Java, users expect subclasses of an expected exception type to also be permitted.

Most (if not all) testing frameworks that I'm familiar with support these semantics.

- JUnit 4: https://github.com/junit-team/junit4/blob/039a24e6afd0527a28d5b5b9e05f118724c97366/src/main/java/org/junit/rules/ExpectedException.java#L194

- JUnit Jupiter: https://github.com/junit-team/junit5/blob/7905cfb0b4e419e23e4ff3cb8ad4b13aa626d022/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java#L58

- TestNG: https://github.com/cbeust/testng/blob/833e521ddfea0f22784d6848a984a2479f6066c7/src/main/java/org/testng/internal/ExpectedExceptionsHolder.java#L53

## Actual Behavior

The `ExpectedExceptionExtension` currently only considers an exact type match.

https://github.com/glytching/junit-extensions/blob/cefd6f4b2fc7972291ad61743a9d9c714c49f321/src/main/java/io/github/glytching/junit/extension/exception/ExpectedExceptionExtension.java#L85

**Comment by glytching** [comment]
As things stand the following test will fail:

```
  @Test
  @ExpectedException(type = Throwable.class, messageIs = "Boom!")
  public void canHandleAThrowable() throws Throwable {
    throw new Exception("Boom!");
  }
```

... because `ExpectedExceptionExtension` applies an exact match on the exception type.

I know (of course :) that `Exception` is a type of `Throwable` but when writing the extension my thinking was:

- Applying an exact match leaves less room for false positives or to put it another way; encourages more specific test cases.
- The exception type can be seen as part of the API and we wouldn't encourage loose assertions on the response type in a non-exception scenario so an exact match on exception type applied the same approach when asserting in the exception scenario.

However, the very useful additional context you supplied makes it clear that this approach is inconsistent with JUnit4 and JUnit5 so I think the consistency principle has to win out here.

I'll change `ExpectedExceptionExtension` such that it allows the given type or subclasses of it (`if (annotation.type().isAssignableFrom(throwable.getClass())) { ... }`).

Thanks for raising the issue.

**Comment by sbrannen** [comment]
👍

**Comment by glytching** [comment]
Raised PR #6

**Comment by glytching** [comment]
Merged, build is green.

Thanks again for taking the time to raise this issue.
